/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.

// Permite importar archivos .css como módulos sin errores de TypeScript
declare module '*.css' {
  const content: string;
  export default content;
}